### PR TITLE
[Improve] Localization streampark-usercase-chinaunion

### PR DESCRIPTION
**Pull request by VampireAchao**
[Improve] Localization streampark-usercase-chinaunion

### CODE REVIEW

**Comment by caicancai** [comment]
@VampireAchao Hello, thank you for your contribution. There should be a corresponding issue for this. Could you please leave a message.
https://github.com/apache/incubator-streampark/issues/3246

**Comment by caicancai** [comment]
close #3246

**Comment by caicancai** [comment]
cc @saLeox

**Comment by VampireAchao** [comment]
> @VampireAchao Hello, thank you for your contribution. There should be a corresponding issue for this. Could you please leave a message.您好，感谢您的贡献。这应该有相应的问题。你能不能留言。 [apache/incubator-streampark#3246apache/孵化器-streampark#3246](https://github.com/apache/incubator-streampark/issues/3246)

ok

**Comment by saLeox** [comment]
LGTM, the translation is well done! thanks for the contribution. @VampireAchao

**Review by wolfboys — APPROVED** [review]
LGTM, good job, Thanks very much for your contribution.

**Pull request merged**
