### PR TITLE
[Improve]Translate the Chinese in the picture into English(chinaunion)

### PR DESCRIPTION
**Pull request by Kick156**

### CODE REVIEW

**Comment by Kick156** [comment]
cc: 抄送：@caicancai @saLeox

**Comment by Kick156** [comment]
see: https://github.com/apache/incubator-streampark/issues/3517

**Comment by VampireAchao** [comment]
Hi, @Kick156 

Thank you for your hard work on the StreamPark project and the improvements made in translating images from Chinese to English.

I'd like to suggest one things:

Internationalization (i18n) Consideration: It would be great if the images could align with the i18n practices. Ideally, when the documentation is switched to Chinese, the images should display in Chinese, and when in English, the images should be in English. This approach could greatly improve the user experience for non-native speakers.

These are just my personal thoughts for your consideration. I look forward to seeing further collaborative progress on the project.

Thanks again for your valuable contribution!

**Comment by caicancai** [comment]
Good job

**Review by caicancai — APPROVED** [review]
LGTM

**Pull request merged**
