### PR TITLE
[Improve] Add code quality rules

### PR DESCRIPTION
**Pull request by wuchunfu**

### CODE REVIEW

**Comment by RocMarshal** [comment]
[review-diff.txt](https://github.com/apache/incubator-streampark-website/files/12651865/review-diff.txt)

**Review by RocMarshal — COMMENTED** [review]
Thank you @wuchunfu very much for advancing it .
So concise and precise!
And I left a review diff file in the comment.
Maybe you could run `git apply review-diff.txt` in the repo root dir to view the diff in the IDE.

Please let me know what's your opinion.

**Comment by wuchunfu** [comment]
@RocMarshal @wolfboys PTAL, thanks.

**Review by RocMarshal — APPROVED** [review]
Thanks for the update.
LGTM +1.

**Pull request merged**
