### PR TITLE
add a new blog

### PR DESCRIPTION
**Pull request by Kick156**
Practice of Unicom Flink Real Time Computing Platform Based Operation and Maintenance

### CODE REVIEW

**Comment by caicancai** [comment]
@Kick156 Hello, thank you very much for your hard work, can you trouble to leave a message under the issue? Prevent others from doing the same task as you. https://github.com/apache/incubator-streampark/issues/3161

**Comment by caicancai** [comment]
cc @wolfboys

**Comment by Kick156** [comment]
> @Kick156 Hello, thank you very much for your hard work, can you trouble to leave a message under the issue? Prevent others from doing the same task as you. [apache/incubator-streampark#3161](https://github.com/apache/incubator-streampark/issues/3161)

Okay, just a moment

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
